require 'rubygems'
require 'bundler'

task :work do
  require 'securerandom'
  require_relative './app/workers/worker'

  key = SecureRandom.uuid

  (1..1_000).each do
    Sidekiq::Client.push_bulk(
      'class' => Worker,
      'args' => (1..1_000).map { [key] }
    )
  end
end
